// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertCloseController from "./alert_close_controller"
application.register("alert-close", AlertCloseController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NumberController from "./number_controller"
application.register("number", NumberController)

import SpotlightController from "./spotlight_controller"
application.register("spotlight", SpotlightController)
